plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.171'
}

version = "${mc_version}-${mod_version}-${tag_lanzador}"
group = "${author}.${modid}"
base {
    archivesName = "${mod_name}"
}

// Java Version
java.toolchain.languageVersion = JavaLanguageVersion.of(21)


runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'

        systemProperty 'forge.logging.console.level', 'debug'
        jvmArgument '-Xmx1G'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', "${modid}"
        argument '--nogui'
    }

    data {
        arguments.addAll '--mod', "${modid}", '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

repositories {
    mavenCentral()
    maven {
        url = 'https://maven.creeperhost.net'
        content {
            includeGroup("com.refinedmods.refinedstorage")
        }
    }
    maven {
        url = "https://maven.blamejared.com"
    }
    maven {
        url = "https://maven.theillusivec4.top/"
    }
    maven {
		name = "TerraformersMC"
		url = "https://maven.terraformersmc.com/"
	}
    maven { url "https://maven.shedaniel.me" }
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        url = uri("https://modmaven.dev/")
        content {
            includeGroup "appeng"
            includeGroup "de.mari_023"
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neoversion}"

    //jei
    implementation "mezz.jei:jei-${mc_version}-common-api:${jei_version}"

}

test {
    enabled = false
}

jar {
    manifest {
        attributes([
                "Specification-Title": archivesBaseName,
                "Specification-Vendor": "${author}",
                "Specification-Version": "1", // We are version 1 of ourselves
                "Implementation-Title": archivesBaseName,
                "Implementation-Version": "${version}",
                "Implementation-Vendor" :"${author}",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mc_version              : mc_version,
            mod_version            : mod_version,
            modid                  : modid,
            author                 : author,
            mod_named              : mod_named,
            tag_lanzador           : tag_lanzador,
            description            : description,
            license                 : license,
            displayURL             : displayURL,
            neoversion             : neoversion,
            loader_version        : loader_version,
            jei_version            : jei_version,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file:///${project.projectDir}/mcmodsrepo"
        }
    }
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    options.getRelease().set(21)
}