org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.215
loader_version_range=[1,)

## Mod Properties
mod_id=ultimatecustomgear
mod_name=Ultimate Custom Gear
mod_license=MIT
mod_version=1.2.4
mod_group_id=arrivedbog593.ultimatecustomgear
author=ArrivedBog593, NadienDev
description=Ultimate Custom Gear is a data-driven mod that allows server owners and modpack creators to add custom armor sets, weapons, tools, food items, blocks and fluids via simple JSON files. No coding required. Supports custom stats, held effects, set bonuses, per-piece armor values, custom textures, crafting recipes and fluid contact effects.
displayURL=https://github.com/ArrivedBog593Dev/UltimateCustomGear

## Dependencies
jei_version=19.27.0.340
