org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

## Mod Properties
modid=ultimatecustomgear
mod_name=UltimateCustomGear
mod_named=Ultimate Custom Gear
tag_lanzador=NeoForge
license=MIT
mod_version=1.2.3
mod_group_id=arrivedbog593
author=ArrivedBog593, NadienDev
description=CustomGear is a data-driven mod that allows server owners and modpack creators to add custom armor sets, weapons, and tools via simple JSON files. No coding required. Supports custom stats, held effects, set bonuses, per-piece armor values, and custom textures.
displayURL=https://github.com/ArrivedBog593Dev/CustomGear

# Minecraft and NeoForge versions
mc_version=1.21.1
neoversion=21.1.215
loader_version=[4,)
java_version=21

# NeoForge Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false


## Dependencies
jei_version=19.27.0.340
